# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

hmc <- function(Time_stamp, Go_RT, Go_RT_S, SSD_min, U, Ind_G, Stop_S_D, sigma, delta_param, gama, beta, stop_param, prob_param, Indicator, mean_priors_main, var_priors_main, penal_param, prior_penal_stop, T_Go, k, T_Total, a, b, prob_hyp, eta_b_l, eta_b_r, eta_nu_l, eta_nu_r, gama_Ind, beta_Ind, nu_d, lam, Phi_mat, rand_param_g_l, rand_param_g_r, rand_param_b_l, rand_param_b_r, kappa, ranges, L, leapmax, nhmc, thin, nparall, l_bound, upper_bound, update_gama_beta, update_penalty, update_stop_prob, update_rand_eff, update_delta, lt = TRUE) {
    .Call(`_BSDDM_hmc`, Time_stamp, Go_RT, Go_RT_S, SSD_min, U, Ind_G, Stop_S_D, sigma, delta_param, gama, beta, stop_param, prob_param, Indicator, mean_priors_main, var_priors_main, penal_param, prior_penal_stop, T_Go, k, T_Total, a, b, prob_hyp, eta_b_l, eta_b_r, eta_nu_l, eta_nu_r, gama_Ind, beta_Ind, nu_d, lam, Phi_mat, rand_param_g_l, rand_param_g_r, rand_param_b_l, rand_param_b_r, kappa, ranges, L, leapmax, nhmc, thin, nparall, l_bound, upper_bound, update_gama_beta, update_penalty, update_stop_prob, update_rand_eff, update_delta, lt)
}

